# Generated by Django 5.0.2 on 2024-03-02 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=25)),
                ('nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MT', 'Mato Grosso'), ('MA', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraiba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondonia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=30)),
                ('hobbies', models.CharField(choices=[('praticar esportes', 'Praticar esportes'), ('desenhar/pintar', 'Desenhar/Pintar'), ('dançar', 'Dançar'), ('conversar', 'Conversar'), ('Meditar', 'Meditar'), ('jogar jogos', 'Jogar jogos'), ('ouvir musica', 'Ouvir musica'), ('outros', 'Outros')], max_length=25)),
                ('linguagens', models.CharField(choices=[('cpp', 'C++'), ('csharp', 'C#'), ('Java', 'java'), ('javascript', 'JavaScript'), ('python', 'Python'), ('ruby', 'Ruby'), ('php', 'PHP'), ('Outros', 'Outros')], max_length=25)),
                ('biografia', models.CharField(max_length=1000)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
