# Generated by Django 5.0.2 on 2024-03-02 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MT', 'Mato Grosso'), ('MA', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraiba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondonia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(choices=[('praticar esportes', 'Praticar esportes'), ('desenhar/pintar', 'Desenhar/Pintar'), ('dançar', 'Dançar'), ('conversar', 'Conversar'), ('Meditar', 'Meditar'), ('jogar jogos', 'Jogar jogos'), ('ouvir musica', 'Ouvir musica'), ('outros', 'Outros')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Linguagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagens', models.CharField(choices=[('cpp', 'C++'), ('csharp', 'C#'), ('Java', 'java'), ('javascript', 'JavaScript'), ('python', 'Python'), ('ruby', 'Ruby'), ('php', 'PHP'), ('Outros', 'Outros')], max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='linguagens',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estados'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='hobby',
            field=models.ManyToManyField(to='core.hobbies'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='linguagem',
            field=models.ManyToManyField(to='core.linguagens'),
        ),
    ]
