# Generated by Django 5.0.1 on 2024-03-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estados_hobbies_linguagens_remove_formulario_hobbies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='nome',
            field=models.CharField(max_length=25),
        ),
    ]
